### ISSUE TITLE
Windows에서 가상 환경 실행 시 보안 오류 발생

### ISSUE THREAD

**Issue by ben020410** [ben020410/safesurf#1]
![image](https://github.com/user-attachments/assets/9c716415-01ca-4974-be9a-31f82bd54f09)
아마 Microsoft의 보안 오류 때문에 발생하는 것으로 보입니다.

**Comment by ben020410** [comment]
다음 명령어를 입력하여 임시로 가상 환경을 허용합니다(터미널에 들어올 때마다 실행하여야 합니다).
```bash
Set-ExecutionPolicy -Scope Process -ExecutionPolicy RemoteSigned
```
이후 `venv\Scripts\activate` 명령어가 잘 동작됨을 확인하실 수 있습니다.

**Comment by jun7431** [comment]
친절한 설명 감사해요
